import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import { SessionProvider } from '../lib/sessionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  session
}: {
  children: React.ReactNode
  session: any
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
        <header className="flex justify-between mx-10 my-6">
          <Link href="/">
            <div className="font-extrabold text-white text-xl">
              Co-Journal
            </div>
          </Link>
          <div>
            <nav className="text-slate-600 dark:text-slate-300">
              <Link href="/entries/new" className="mx-6">write</Link>
              <Link href="/entries" className="mx-6">entries</Link>
            </nav>
          </div>
        </header>
        {children}
        </SessionProvider>
      </body>
    </html>
  )
}
